apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
  namespace: maniaque
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
        - name: mongo-express
          image: mongo-express:latest
          ports:
            - containerPort: 8081
          env:
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              value: "root"  # Username, defined in MongoDB deployment
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              value: "password"  # Password, defined in MongoDB deployment
            - name: ME_CONFIG_MONGODB_SERVER
              value: "mongo-service"  # Service name for MongoDB
            - name: ME_CONFIG_MONGODB_ENABLE_ADMIN
              value: "true"  # Allow connecting as admin
            - name: ME_CONFIG_BASICAUTH_USERNAME
              value: "admin"  # Username for Basic Auth (Mongo-Express UI)
            - name: ME_CONFIG_BASICAUTH_PASSWORD
              value: "adminpass"  # Password for Basic Auth (Mongo-Express UI)
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"